version: "3"

services:
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
      - static_volume:/backend/django_static  # <-- bind the static volume
      - media_volume:/backend/django_media  # <-- bind the media volume
    env_file:
      - ./.prod
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - backend
    volumes:
      - static_volume:/backend/django_static  # <-- bind the static volume
      - media_volume:/backend/django_media  # <-- bind the media volume

volumes:
  static_volume:  # <-- declare the static volume
  media_volume:  # <-- declare the media volume