version: '3.7'
volumes:
  node_modules:
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/backend
    ports:
      - 8000:8000
      - 5678:5678
    tty: true
    env_file:
      - ./.dev
    restart: always
    # command: python leadmanager/manage.py runserver 0.0.0.0:8000
  frontend:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    tty: true
    volumes:
      # - /frontend/node_modules
      - ./frontend:/frontend
      # - ./frontend/node_modules:/frontend/node_modules
    ports:
      - 3000:3000
    command: yarn start
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:3050'
    depends_on:
      - frontend