FROM python:3.9-slim-buster
LABEL Luis Andia

ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip
# RUN pip install pipenv
# RUN pip install virtualenv

# WORKDIR /backend


# ENV VIRTUAL_ENV=.venv
# RUN python -m venv $VIRTUAL_ENV
# ENV PATH="$VIRTUAL_ENV/bin:$PATH"
# RUN pip install virtualenv
# RUN pipenv shell
# RUN PIPENV_VENV_IN_PROJECT=1 pipenv sync -d

COPY ./requirements.txt /requirements.txt


RUN pip install -r /requirements.txt
# RUN . .venv/bin/activate
WORKDIR /backend
# COPY . .

CMD sh ./script.sh

# RUN useradd -ms /bin/bash user
# USER user